hmcts/chart-neuvector

templates/configmap.yaml
templates/post-install-job.yaml

[[AB#194](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/194)]
```
[ ] Yes
[x] No
```

Add slack webhook

---

ci-values.yaml
neuvector-azure-keyvault/templates/configmap.yaml
neuvector-azure-keyvault/values.yaml

[[AB#467](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/467)]
Response rules automation
```
[ ] Yes
[x] No
```

Response rules

---

neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/post-install-job.yaml

[[AB#194](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/194)]
```
[ ] Yes
[x] No
```

Run job also post upgrade

---

neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/configmap.yaml

Check eula before accepting

---

neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/configmap.yaml

[[AB#194](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/194)]
```
[ ] Yes
[x] No
```

Check license before updating

---

ci-values.yaml
neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/configmap.yaml
neuvector-azure-keyvault/values.yaml

[[AB#574](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/574)]
```
[ ] Yes
[x] No
```

Add auto-scan

---

.gitmodules
neuvector-azure-pipelines.yml

[AB#640](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/640)
```
[ ] Yes
[ ] No
```

Update to latest neuvector chart

---

ci-values.yaml
neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/requirements.yaml
neuvector-azure-keyvault/templates/configmap.yaml
neuvector-azure-keyvault/templates/post-install-job.yaml
neuvector-azure-keyvault/templates/tests/test-service.yaml
neuvector-azure-keyvault/values.yaml

[AB#640](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/640) Upgrade neuvector
```
[ ] Yes
[ ] No
```

Upgrade neuvector

---

ci-values.yaml
neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/configmap.yaml
neuvector-azure-keyvault/templates/post-install-job.yaml
neuvector-azure-keyvault/values.yaml

[[AB#742](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/742)]
```
[ ] Yes
[x] No
```

Fix get admission rule issue. Clean up

---

ci-values.yaml
neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/configmap.yaml

[[AB#742](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/742)]
```
[ ] Yes
[x] No
```

Fix offsets to avoid clashes with current values

---

azure-pipelines.yml
ci-values.yaml
neuvector-azure-keyvault/templates/configmap.yaml
neuvector-azure-keyvault/values.yaml
neuvector-azure-pipelines.yml

delay config script loading

---

neuvector-azure-keyvault/templates/configmap.yaml
neuvector-azure-keyvault/values.yaml

https://tools.hmcts.net/jira/browse/DTSPO-25

dtspo:25 Access via  http protocol

---

azure-pipelines.yml
ci-values.yaml
neuvector-azure-keyvault/templates/configmap.yaml
neuvector-azure-keyvault/values.yaml

https://tools.hmcts.net/jira/browse/DTSPO-25

dtspo:25 added end statement

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/DTSPO-25

Dtspo:25 automate neuvector

---

neuvector-azure-keyvault/templates/configmap.yaml

Or at least it's not documented...

DTSPO-25 Controller API url doesn't support http mode

---

neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/post-install-job.yaml
neuvector-azure-keyvault/templates/secretproviderclass.yaml
neuvector-azure-keyvault/templates/tests/test-service.yaml

Upgrade chart library

---

README.md
neuvector-azure-keyvault/templates/configmap.yaml
neuvector-azure-keyvault/values.yaml

Force Update flag to use for renewal

---

neuvector-azure-keyvault/templates/configmap.yaml

Fix condition for licenseforceupgrade

---

azure-pipelines.yml
neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/secretproviderclass.yaml

https://tools.hmcts.net/jira/browse/DTSPO-10284
Upgrade hmcts library base chart to newest version, upgrade the secretproviderclass.tpl dependency brought in from library to v3 to get past breaking change in library chart versions
revert helminstall timeout
```
[ ] Yes
[x] No
```

Upgrade library dependency to newest, upgrade secretproviderclass to fix breaking change, revert helminstall timeout

---

azure-pipelines.yml
ci-values.yaml
neuvector-azure-keyvault/values.yaml

DTSPO-14808
Test preview cluster
```
[ ] Yes
[x] No
```

test preview cluster

---

azure-pipelines.yml
ci-values.yaml
neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/post-install-job.yaml
neuvector-azure-keyvault/templates/secretproviderclass.yaml
neuvector-azure-keyvault/templates/tests/test-service.yaml
neuvector-azure-keyvault/values.yaml

Update neuvector to release 2.6.1
```
[ ] Yes
[X] No
```

Update neuvector to release 2.6.1

---

azure-pipelines.yml

Changed to be the default in https://github.com/hmcts/cnp-azuredevops-libraries/pull/176

Remove helm version override

---

neuvector-azure-keyvault/values.yaml

DTSPO-14808
Move updater image under cve section

move updater under cve

---

neuvector-azure-keyvault/Chart.yaml

see https://github.com/hmcts/sds-flux-config/pull/3595

Move CRDs to flux

---

neuvector-azure-keyvault/templates/admission-control.yaml

https://tools.hmcts.net/jira/browse/DTSPO-16874
Adding Namespace Artifactory

DTSPO-16874: Adding Namespace Artifactory

---

neuvector-azure-keyvault/templates/admission-control.yaml

https://tools.hmcts.net/jira/browse/DTSPO-17730
Remove references to sdshmctsprivate

DTSPO-17730 - remove refrences to sdshmctsprivate

---

neuvector-azure-keyvault/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPO-17592
Updating to latest Neuvector dependency version

Update neuvector version

---

neuvector-azure-keyvault/Chart.yaml

- bump version in chart
- pact-broker in admin admission-control already in master

bump version number

---

azure-pipelines.yml

See [DTSPO-22727](https://tools.hmcts.net/jira/browse/DTSPO-22727)
Release pipeline is failing to log into the default ACR "hmctspublic". This PR overrides the default ACR to use "hmctssandbox"
instead.

Change default ACR name to "hmctssandbox"

---

azure-pipelines.yml

See [DTSPO-22727](https://tools.hmcts.net/jira/browse/DTSPO-22727)

Point pipeline to custom branch

---

neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/admission-control.yaml

https://tools.hmcts.net/jira/browse/DTSPO-23618
- Allowing deployments from `hmctsprivatetemp` ACR 
- Part of a workaround for above issue

Allow temp ACR

---

neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/admission-control.yaml

Reverts hmcts/chart-neuvector#90

Revert "Allow temp ACR"

---

neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/admission-control.yaml

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

Add acr to allow list

---

neuvector-azure-keyvault/Chart.yaml

N/A
Bumps Neuvector version to 2.8.4

Bump neuvctor version

---

neuvector-azure-keyvault/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPO-26052
Bumps Neuvector version to 2.8.6
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

Bumps Neuvector version to 2.8.6

---

neuvector-azure-keyvault/Chart.yaml
neuvector-azure-keyvault/templates/configmap.yaml

Reverts hmcts/chart-neuvector#104 - test the pipeline

Revert "Configmap patch"
